spring.application.name=tenant-service
server.port=8082
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel_tenant
spring.datasource.username=postgres
spring.datasource.password=postgres

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Auth Service URL (para validar JWT)
services.auth.url=http://localhost:8081

# Tenant Events
tenant.events.exchange=tenant-exchange
tenant.events.created-routing-key=tenant.created